version: '3.1'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: to_do_list
      MYSQL_ROOT_PASSWORD: epicodus
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: